/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'linkedDoctorId' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'note' : IDL.Text,
  'dueDate' : IDL.Int,
  'isDone' : IDL.Bool,
});
export const VisitOutcome = IDL.Variant({
  'negative' : IDL.Null,
  'positive' : IDL.Null,
  'neutral' : IDL.Null,
});
export const Visit = IDL.Record({
  'id' : IDL.Nat,
  'doctorId' : IDL.Nat,
  'productsDiscussed' : IDL.Vec(IDL.Nat),
  'callNotes' : IDL.Text,
  'date' : IDL.Int,
  'nextVisitDate' : IDL.Opt(IDL.Int),
  'outcome' : VisitOutcome,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'areaTerritory' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'specialty' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'clinicName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'keyBenefits' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'territory' : IDL.Text,
  'name' : IDL.Text,
  'employeeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReminder' : IDL.Func([Reminder], [], []),
  'createVisit' : IDL.Func([Visit], [], []),
  'deleteDoctor' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteVisit' : IDL.Func([IDL.Nat], [], []),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalDoctors' : IDL.Nat,
          'visitsThisMonth' : IDL.Nat,
          'pendingReminders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDoctor' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getReminder' : IDL.Func([IDL.Nat], [IDL.Opt(Reminder)], ['query']),
  'getTodaysVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisit' : IDL.Func([IDL.Nat], [IDL.Opt(Visit)], ['query']),
  'getVisitsByDoctor' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markReminderDone' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateReminder' : IDL.Func([IDL.Nat, Reminder], [], []),
  'updateVisit' : IDL.Func([IDL.Nat, Visit], [], []),
  'upsertDoctor' : IDL.Func([Doctor], [IDL.Nat], []),
  'upsertProduct' : IDL.Func([Product], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'linkedDoctorId' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'note' : IDL.Text,
    'dueDate' : IDL.Int,
    'isDone' : IDL.Bool,
  });
  const VisitOutcome = IDL.Variant({
    'negative' : IDL.Null,
    'positive' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const Visit = IDL.Record({
    'id' : IDL.Nat,
    'doctorId' : IDL.Nat,
    'productsDiscussed' : IDL.Vec(IDL.Nat),
    'callNotes' : IDL.Text,
    'date' : IDL.Int,
    'nextVisitDate' : IDL.Opt(IDL.Int),
    'outcome' : VisitOutcome,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'areaTerritory' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'specialty' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'clinicName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'keyBenefits' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'territory' : IDL.Text,
    'name' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReminder' : IDL.Func([Reminder], [], []),
    'createVisit' : IDL.Func([Visit], [], []),
    'deleteDoctor' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteVisit' : IDL.Func([IDL.Nat], [], []),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalDoctors' : IDL.Nat,
            'visitsThisMonth' : IDL.Nat,
            'pendingReminders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDoctor' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getReminder' : IDL.Func([IDL.Nat], [IDL.Opt(Reminder)], ['query']),
    'getTodaysVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisit' : IDL.Func([IDL.Nat], [IDL.Opt(Visit)], ['query']),
    'getVisitsByDoctor' : IDL.Func([IDL.Nat], [IDL.Vec(Visit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markReminderDone' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateReminder' : IDL.Func([IDL.Nat, Reminder], [], []),
    'updateVisit' : IDL.Func([IDL.Nat, Visit], [], []),
    'upsertDoctor' : IDL.Func([Doctor], [IDL.Nat], []),
    'upsertProduct' : IDL.Func([Product], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };