/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Doctor {
  'id' : bigint,
  'areaTerritory' : string,
  'name' : string,
  'email' : string,
  'specialty' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'clinicName' : string,
}
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'keyBenefits' : string,
}
export interface Reminder {
  'id' : bigint,
  'linkedDoctorId' : [] | [bigint],
  'title' : string,
  'note' : string,
  'dueDate' : bigint,
  'isDone' : boolean,
}
export interface UserProfile {
  'territory' : string,
  'name' : string,
  'employeeId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : bigint,
  'doctorId' : bigint,
  'productsDiscussed' : Array<bigint>,
  'callNotes' : string,
  'date' : bigint,
  'nextVisitDate' : [] | [bigint],
  'outcome' : VisitOutcome,
}
export type VisitOutcome = { 'negative' : null } |
  { 'positive' : null } |
  { 'neutral' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReminder' : ActorMethod<[Reminder], undefined>,
  'createVisit' : ActorMethod<[Visit], undefined>,
  'deleteDoctor' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteReminder' : ActorMethod<[bigint], undefined>,
  'deleteVisit' : ActorMethod<[bigint], undefined>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllReminders' : ActorMethod<[], Array<Reminder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalDoctors' : bigint,
      'visitsThisMonth' : bigint,
      'pendingReminders' : bigint,
    }
  >,
  'getDoctor' : ActorMethod<[bigint], [] | [Doctor]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getReminder' : ActorMethod<[bigint], [] | [Reminder]>,
  'getTodaysVisits' : ActorMethod<[], Array<Visit>>,
  'getUpcomingReminders' : ActorMethod<[], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisit' : ActorMethod<[bigint], [] | [Visit]>,
  'getVisitsByDoctor' : ActorMethod<[bigint], Array<Visit>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markReminderDone' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateReminder' : ActorMethod<[bigint, Reminder], undefined>,
  'updateVisit' : ActorMethod<[bigint, Visit], undefined>,
  'upsertDoctor' : ActorMethod<[Doctor], bigint>,
  'upsertProduct' : ActorMethod<[Product], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];